# Generated by Django 3.0.3 on 2020-02-04 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_login_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_method', models.CharField(choices=[('github', 'Github'), ('kakao', 'Kakao')], max_length=50)),
                ('id_kakao', models.CharField(max_length=30)),
                ('kaccount_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kakao Login ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='kakao')),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='kakao')),
                ('nickname', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kakao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
