# Generated by Django 3.0.3 on 2020-02-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_auto_20200205_1449'),
        ('users', '0003_kakaouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_bookshelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shelves.BookShelf'),
        ),
    ]
