# Generated by Django 3.0.3 on 2020-02-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_current_bookshelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
