# Generated by Django 3.0.3 on 2020-02-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200206_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KakaoUser',
        ),
    ]
