# Generated by Django 3.0.3 on 2020-02-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_kakaouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User6149', max_length=20),
        ),
    ]
