# Generated by Django 3.0.3 on 2020-02-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_auto_20200205_1449'),
        ('users', '0007_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_bookshelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelves.BookShelf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User3700', max_length=20),
        ),
    ]
