version: '3' 
services: 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    command: python manage.py runserver 127.0.0.1:8000
    volumes: 
      - .:/code 
    env_file:
      - ./.env
    expose:
      - "8000"
