version: '3' 
services: 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    command: daphne config.asgi:application --bind 0.0.0.0 -p 8000
    volumes: 
      - .:/code 
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    expose:
      - "8000"
  redis:
    image: redis:alpine
