# Generated by Django 3.0.2 on 2020-01-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=100)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('isbn', models.IntegerField(unique=True)),
                ('kdc', models.CharField(max_length=10)),
            ],
        ),
    ]
