# Generated by Django 3.0.3 on 2020-02-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(default='', max_length=500)),
                ('author', models.CharField(default='', max_length=200)),
                ('publisher', models.CharField(default='', max_length=100)),
                ('pub_year', models.CharField(default='', max_length=20)),
                ('volume', models.CharField(default='', max_length=10)),
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('kdc', models.CharField(default='', max_length=10)),
                ('description', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
