# Generated by Django 3.0.2 on 2020-01-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
