# Generated by Django 3.0.3 on 2020-02-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200210_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(blank=True, upload_to='bookImage'),
        ),
    ]
