# Generated by Django 3.0.3 on 2020-02-10 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_bookimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='kdc',
        ),
        migrations.RemoveField(
            model_name='book',
            name='volume',
        ),
    ]
