# Generated by Django 3.0.3 on 2020-02-10 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200210_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.date(2020, 2, 10)),
            preserve_default=False,
        ),
    ]
