# Generated by Django 3.0.3 on 2020-02-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200210_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(blank=True, null=True, upload_to='bookImage'),
        ),
    ]
