# Generated by Django 3.0.3 on 2020-02-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200226_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
