# Generated by Django 3.0.3 on 2020-02-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_num_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
