# Generated by Django 3.0.3 on 2020-03-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['-weight']},
        ),
    ]
