# Generated by Django 3.0.3 on 2020-03-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_auto_20200303_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['-num_view']},
        ),
        migrations.AddField(
            model_name='keyword',
            name='num_view',
            field=models.IntegerField(default=0),
        ),
    ]
