# Generated by Django 3.0.3 on 2020-03-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_auto_20200303_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['word']},
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='num_view',
        ),
    ]
