# Generated by Django 3.0.3 on 2020-02-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybook',
            old_name='user',
            new_name='bookshelf',
        ),
    ]
