# Generated by Django 3.0.3 on 2020-02-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_bookshelf_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
