# Generated by Django 3.0.3 on 2020-02-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_auto_20200205_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='name',
            field=models.CharField(default='My Bookshelf', max_length=30),
        ),
    ]
