# Generated by Django 3.0.3 on 2020-02-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_auto_20200205_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not provided')], default='N', max_length=1),
        ),
    ]
