# Generated by Django 3.0.3 on 2020-02-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_auto_20200211_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='current_page',
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='total_page',
        ),
        migrations.AlterField(
            model_name='mybook',
            name='star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
