# Generated by Django 3.0.3 on 2020-02-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_auto_20200211_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='page',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
