# Generated by Django 3.0.3 on 2020-02-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0007_auto_20200217_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shelves.MyBook'),
        ),
    ]
