# Generated by Django 3.0.3 on 2020-02-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0008_auto_20200218_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
