# Generated by Django 3.0.3 on 2020-02-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0009_delete_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybook',
            options={'ordering': ['-created_at']},
        ),
    ]
